function draw_map(Mobj)
% draw two dimension map

figure('color','w')

patch('Vertices',[Mobj.x,Mobj.y],...
    'Faces',Mobj.triangle_topology,...
    'Cdata',Mobj.h,...
    'edgecolor','none',...
    'facecolor','interp');
axis('equal','tight')

end